# Generated by Django 2.2.1 on 2019-06-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edrs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EDRScoutMotor',
        ),
    ]
