# Generated by Django 2.2.1 on 2019-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrs', '0002_delete_edrscoutmotor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edrraw',
            name='hole_depth',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='edrraw',
            name='rop_a',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='edrraw',
            name='rop_i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
