# Generated by Django 2.2.1 on 2019-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrs', '0004_auto_20190630_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='edrprocessed',
            name='cxn_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
