# Generated by Django 2.2.1 on 2019-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrs', '0006_auto_20190630_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edrdrilled',
            name='bit_rpm',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='edrdrilled',
            name='normalized_tf',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
