# Generated by Django 2.2.1 on 2019-06-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('well_api', models.CharField(blank=True, max_length=14, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('spud_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('sses_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='WellConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('well_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rig_name', models.CharField(blank=True, max_length=50, null=True)),
                ('data_frequency', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_well_connectors', to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hole_size', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('start_depth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('end_depth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cased', models.BooleanField(default=False)),
                ('casing_size', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_intervals', to='jobs.Job')),
            ],
            options={
                'verbose_name_plural': 'Intervals',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_depth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('end_depth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rock_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pore_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mud_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_formations', to='jobs.Job')),
            ],
            options={
                'verbose_name_plural': 'Formations',
            },
        ),
    ]
