# Generated by Django 2.2.1 on 2019-07-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190630_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellconnector',
            name='uidWellbore',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
