# Generated by Django 2.2.1 on 2019-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_wellconnector_uidwellbore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellconnector',
            name='uidWellbore',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wellconnector',
            name='well_name',
            field=models.CharField(max_length=50),
        ),
    ]
