# Generated by Django 2.2.1 on 2019-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190701_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellconnector',
            name='chron_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wellconnector',
            name='data_valid',
            field=models.BooleanField(default=False),
        ),
    ]
