# Generated by Django 2.2.1 on 2019-08-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190731_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellconnector',
            options={'verbose_name_plural': 'Well Connectors'},
        ),
        migrations.RenameField(
            model_name='wellconnector',
            old_name='chron_on',
            new_name='cron_on',
        ),
    ]
