# Generated by Django 2.2.1 on 2019-06-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('bha_number', models.IntegerField(blank=True, null=True)),
                ('bha_length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('depth_in', models.IntegerField()),
                ('depth_out', models.IntegerField(blank=True, null=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('drill_time_start', models.DateTimeField(blank=True, null=True)),
                ('drill_time_end', models.DateTimeField(blank=True, null=True)),
                ('hole_size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('survey_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('gamma_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('resistivity_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('shock_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('pressure_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('nb_gamma_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('nb_inc_distance', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('downhole_hrs', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('circulating_hrs', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('drilling_hrs', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('sliding_hrs', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rotating_hrs', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('feet_slid', models.CharField(blank=True, max_length=50, null=True)),
                ('feet_rotated', models.CharField(blank=True, max_length=50, null=True)),
                ('total_rop', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('inc_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('inc_out', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('azi_in', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('azi_out', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('dogleg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('motor_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('build_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('turn_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('sliding_rop', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rotating_rop', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('footage_drilled', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_bhas', to='jobs.Job')),
            ],
            options={
                'verbose_name_plural': 'Bhas',
            },
        ),
    ]
