# Generated by Django 2.2.1 on 2019-06-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bha',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
