# Generated by Django 2.2.1 on 2019-06-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('md', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inc', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('azi', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tvd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('north', models.DecimalField(decimal_places=2, max_digits=10)),
                ('east', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vertical_section', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dogleg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('my', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('build_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turn_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bitto_sensor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sli_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_tf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.NullBooleanField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_projections', to='jobs.Job')),
            ],
            options={
                'verbose_name_plural': 'Projections',
            },
        ),
    ]
