# Generated by Django 2.2.1 on 2019-06-26 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('level', models.CharField(default='0', max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('e_contact_first_name', models.CharField(max_length=50)),
                ('e_contact_last_name', models.CharField(max_length=50)),
                ('e_contact_cell_phone', phone_field.models.PhoneField(help_text='Contact Phone Number', max_length=31)),
                ('e_contact_work_phone', phone_field.models.PhoneField(help_text='Contact Phone Number', max_length=31)),
                ('e_contact_relationship', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personnel',
            },
        ),
    ]
